/*
5. Modify the program shown in Example 10.30 (compound interest calculations) (Page 11.44) of
text book (Byron Gottfried) so that it generates a table of F-values for various time periods,
using different compounding frequencies. Assume that A and n are input values. Display the
output in the following manner.
A = . . .
i = . . .
Interest rate = 5% 6% 7% 8% 9% 10% 11% 12% 13% 14% 15%
Frequency of
Compounding
Annual --- --- --- --- --- --- --- --- --- --- ---
Semiannual --- --- --- --- --- --- --- --- --- --- ---
Quarterly --- --- --- --- --- --- --- --- --- --- ---
Monthly --- --- --- --- --- --- --- --- --- --- ---
Daily --- --- --- --- --- --- --- --- --- --- ---
Continuously --- --- --- --- --- --- --- --- --- --- ---
Notice that the first four rows are generated by one function with different arguments, and each of
the last two rows is generated by a different function.
a. Repeat the previous problem, but transpose the table so that each row represents a different
value for n and each column represents a different compounding frequency. Consider
integer values of n ranging from 1 to 50. Note that this table will consist of 50 rows and 6
columns. (Hint: Generate the table by columns, storing each column in a two-dimensional
array. Display the entire array after all the values have been generated.)
b. Compare the programming effort required for this problem with the programming effort
required for the preceding problem.
*/

#include<stdio.h>
#include<stdlib.h>
#include<ctype.h>
#include<math.h>

void table(double (*pf)(double i, int m, double n),double a, int m, double n);
double md1(double i, int m, double n);
double md2(double i, int m, double n);
double md3(double i, int m, double n);

void main(){
	int m,count,cpd;
	double n,a;
	char freq;
	printf("\nFuture Value of a series of Monthly Deposits.\n");
	printf("Enter the amount of each monthly payment: ");
	scanf("%lf",&a);
	printf("\nNumber of years money is saved: ");
	scanf("%lf",&n);
	printf("\nInterest Rate = ");
	for (count = 5; count <= 15; ++count) {
		printf ( " %2d",count) ;
		printf("%%");
		}
	printf("\n");
	printf("Frequency of Compounding\n");
	for(cpd=1;cpd<=6;cpd++){
		switch(cpd){
			case 1:
					m=1;
					printf("\nAnnual ");
					table(md1,a,m,n);
					break;
			case 2:
					m=2;
					printf("\nSemi-Annual ");
					table(md1,a,m,n);
					break;
			case 3:
					m=4;
					printf("\nQuarterly ");
					table(md1,a,m,n);
					break;
			case 4:
					m=12;
					printf("\nMonthly ");
					table(md1,a,m,n);
					break;
			case 5:
					m=360;
					printf("\nDaily ");
					table(md2,a,m,n);
					break;
			case 6:
					m=0;
					printf("\nContinuous ");
					table(md3,a,m,n);
					break;
		}	
	
	}
}
	
void table(double (*pf)(double i, int m, double n), double a, int m, double n)
// table generator (this function accepts a pointer to another function as an argument)
{
	int count,cpd; 
	double i; //annual interest rate
	double f; //future value
		for(count =5; count<= 15; count++){
			i= 0.01 * count;
			f = a * (*pf)(i, m, n);/* ACCESS THE FUNCTION PASSED AS A POINTER */
			printf("  %.2f",f);
		}
	
}

double md1(double i, int m, double n)
/* monthly deposits, periodic compounding */
	{
	double factor, ratio;
	factor = 1 + i/m;
	ratio = 12 * (pow(factor, m*n) - 1) / i;
	return(ratio);
	}

double md2(double i,int m, double n)
/* monthly deposits, daily compounding */
	{
	double factor, ratio;
	factor = 1 + i/m;
	ratio = (pow(factor, m*n) - 1) / (pow(factor, m/12) - 1);
	return(ratio);
	} 

double md3(double i,int dummy, double n)
/* monthly deposits, continuous compounding */
	{
	double ratio;
	ratio = (exp(i*n) - 1) / (exp(i/12) - 1);
	return(ratio); 
	}
	
/*
[root@sel-25 196 CSE C]# ./c

Future Value of a series of Monthly Deposits.
Enter the amount of each monthly payment: 100

Number of years money is saved: 3

Interest Rate =   5%  6%  7%  8%  9% 10% 11% 12% 13% 14% 15%
Frequency of Compounding

Annual   3783.00  3820.32  3857.88  3895.68  3933.72  3972.00  4010.52  4049.28 4088.28  4127.52  4167.00
Semi-Annual   3832.64  3881.05  3930.09  3979.79  4030.13  4081.15  4132.83  4185.19  4238.24  4291.97  4346.41
Quarterly   3858.11  3912.36  3967.53  4023.63  4080.67  4138.67  4197.64  4257.61  4318.59  4380.59  4443.63
Monthly   3875.33  3933.61  3993.01  4053.56  4115.27  4178.18  4242.31  4307.69  4374.33  4442.28  4511.55
Daily   3875.92  3934.47  3994.20  4055.14  4117.31  4180.75  4245.48  4311.53  4378.93  4447.72  4517.92
Continuous   3875.94  3934.49  3994.24  4055.19  4117.38  4180.84  4245.59  4311.66  4379.09  4447.91  4518.14
*/